FROM node:16-alpine as builder

WORKDIR /app

COPY ./frontend/scanner-ui ./

RUN npm install
RUN npm run build

FROM nginx:alpine

COPY --from=builder /app/build /usr/share/nginx/html

EXPOSE 80

ENTRYPOINT ["nginx", "-g", "daemon off;"]